#
###################################
# Site wide configuration
####################################
#

title: Evance 
email: evanxg852000@gmail.com
description: A collection of my internet rumblings.
url: # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
timezone:          Africa/Conakry
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
#permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

paginate: 5

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Evance Soumaoro
  avatar: evanxg-logo.png
  job: "Senior Software Developer"
  bio: "IT professional interested in low level programming, mostly language implementation. Extensive experience in API design and implementation in C++, C#, Java, NodeJS and PHP."
  email: evanxg852000@gmail.com
  disqus-shortname: evanxg852000-github-io
  twitter: evanxg852000
  github: evanxg852000
  stackoverflow: 1304832/evanxg852000
  linkedin: #username

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jemoji
